//
// --------------------------------------------------------------------------
//  Gurux Ltd
//
//
//
// Filename:        $HeadURL$
//
// Version:         $Revision$,
//                  $Date$
//                  $Author$
//
// Copyright (c) Gurux Ltd
//
//---------------------------------------------------------------------------
//
//  DESCRIPTION
//
// This file is a part of Gurux Device Framework.
//
// Gurux Device Framework is Open Source software; you can redistribute it
// and/or modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2 of the License.
// Gurux Device Framework is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// This code is licensed under the GNU General Public License v2.
// Full text may be retrieved at http://www.gnu.org/licenses/gpl-2.0.txt
//---------------------------------------------------------------------------

using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;

namespace Gurux.DLMS.AMI.Shared
{
    /// <summary>
    /// This class implements helper functions to communicate with Gurux.DLMS.AMI.Server.
    /// </summary>
    public static class Helpers
    {
        /// <summary>
        /// A machine-readable format for specifying errors in HTTP API responses based on <see href="https://tools.ietf.org/html/rfc7807"/>.
        /// </summary>
        private class ProblemDetails
        {
            /// <summary>
            /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
            /// dereferenced, it provide human-readable documentation for the problem type
            /// (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be
            /// "about:blank".
            /// </summary>
            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyOrder(-5)]
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            /// <summary>
            /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
            /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
            /// see[RFC7231], Section 3.4).
            /// </summary>
            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyOrder(-4)]
            [JsonPropertyName("title")]
            public string? Title { get; set; }

            /// <summary>
            /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
            /// </summary>
            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyOrder(-3)]
            [JsonPropertyName("status")]
            public int? Status { get; set; }

            /// <summary>
            /// A human-readable explanation specific to this occurrence of the problem.
            /// </summary>
            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyOrder(-2)]
            [JsonPropertyName("detail")]
            public string? Detail { get; set; }

            /// <summary>
            /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
            /// </summary>
            [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
            [JsonPropertyOrder(-1)]
            [JsonPropertyName("instance")]
            public string? Instance { get; set; }

            /// <summary>
            /// Gets the <see cref="IDictionary{TKey, TValue}"/> for extension members.
            /// <para>
            /// Problem type definitions MAY extend the problem details object with additional members. Extension members appear in the same namespace as
            /// other members of a problem type.
            /// </para>
            /// </summary>
            /// <remarks>
            /// The round-tripping behavior for <see cref="Extensions"/> is determined by the implementation of the Input \ Output formatters.
            /// In particular, complex types or collection types may not round-trip to the original type when using the built-in JSON or XML formatters.
            /// </remarks>
            [JsonExtensionData]
            public IDictionary<string, object?> Extensions { get; set; } = new Dictionary<string, object?>(StringComparer.Ordinal);
        }

        /// <summary>
        /// Validate server reply status code.
        /// </summary>
        public static async Task ValidateStatusCode(HttpResponseMessage response, 
            CancellationToken cancellationToken)
        {
            if (!response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync(cancellationToken);
                ProblemDetails? problem;
                try
                {
                    problem = JsonSerializer.Deserialize<ProblemDetails>(content);
                }
                catch
                {
                    throw new Exception(content);
                }
                throw new Exception(problem?.Detail ?? problem?.Title ?? content);
            }
        }

        /// <summary>
        /// Post object as JSON to the server.
        /// </summary>
        /// <returns>Server reply.</returns>
        public static async Task<RET> PostAsJson<RET>(this HttpClient client, string requestUri, object value, CancellationToken cancellationToken = default)
        {
            JsonSerializerOptions options = new JsonSerializerOptions()
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault
            };
            HttpResponseMessage response = await client.PostAsJsonAsync(requestUri, value, options, cancellationToken);
            await ValidateStatusCode(response, cancellationToken);
            var ret = await response.Content.ReadFromJsonAsync<RET>();
            if (ret == null)
            {
                throw new Exception("Invalid reply.");
            }
            return ret;
        }

        /// <summary>
        /// Post object as JSON to the server.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="requestUri"></param>
        /// <param name="value"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>Server reply.</returns>
        public static async Task PostAsJson(this HttpClient client, string requestUri, object value, CancellationToken cancellationToken = default)
        {
            JsonSerializerOptions options = new JsonSerializerOptions()
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault
            };
            HttpResponseMessage response = await client.PostAsJsonAsync(requestUri, value, options, cancellationToken);
            await ValidateStatusCode(response, cancellationToken);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <typeparam name="RET"></typeparam>
        /// <param name="client"></param>
        /// <returns>Server reply.</returns>
        public static async Task<RET> GetAsJsonAsync<RET>(this HttpClient client, string requestUri, CancellationToken cancellationToken = default)
        {
            HttpResponseMessage response = await client.GetAsync(requestUri, cancellationToken);
            await ValidateStatusCode(response, cancellationToken);
            var ret = await response.Content.ReadFromJsonAsync<RET>();
            if (ret == null)
            {
                throw new Exception("Invalid reply.");
            }
            return ret;
        }

        /// <summary>
        /// Get objects properties as a string.
        /// </summary>
        /// <param name="target">Target object.</param>
        /// <returns>Target properties as a string.</returns>
        public static string GetProperties(object target)
        {
            StringBuilder sb = new StringBuilder();
            foreach (var it in target.GetType().GetProperties())
            {
                sb.AppendLine(it.Name + ": " + it.GetValue(target));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Get objects properties as a string.
        /// </summary>
        /// <param name="target">Target object.</param>
        /// <returns>Target properties as a string.</returns>
        public static Dictionary<string, object?> GetDictionaryProperties(object target)
        {
            Dictionary<string, object?> list = new Dictionary<string, object?>();
            foreach (var it in target.GetType().GetProperties())
            {
                list.Add(it.Name, it.GetValue(target));
            }
            return list;
        }
    }
}
